#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#./Allrun.pre

# Decompose
runApplication decomposePar -force

# Run
runParallel ../../solver/openCrys

# Reconstruct
runApplication reconstructPar -noFunctionObjects

# ----------------------------------------------------------------- end-of-file
